app_resit/aplicaciones/cliente/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.cliente.views import ClienteList,ClienteCreate, ClienteUpdate, ClienteDelete

urlpatterns = [
		
	  url(r'^nuevo$', ClienteCreate.as_view(), name ='cliente_crear'),  
      url(r'^$', ClienteList.as_view(), name ='cliente_listar'),
      url(r'^listar$', ClienteList.as_view(), name ='cliente_listar'),

      url(r'^editar/(?P<pk>\w+)/$', ClienteUpdate.as_view(), name ='cliente_editar'),
      url(r'^eliminar/(?P<pk>\w+)/$', ClienteDelete.as_view(), name ='cliente_eliminar'),
      



    ]

app_resit/aplicaciones/pedido/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.pedido.views import PedidoCreate, PedidoList, PedidoUpdate , PedidoDelete

urlpatterns = [

    	url(r'^nuevo$', PedidoCreate.as_view(), name ='pedido_crear'),
      	url(r'^$', PedidoList.as_view(), name ='pedido_listar'),
      	url(r'^listar$', PedidoList.as_view(), name ='pedido_listar'),


      url(r'^editar/(?P<pk>\d+)/$', PedidoUpdate.as_view(), name ='pedido_editar'),
      url(r'^eliminar/(?P<pk>\d+)/$', PedidoDelete.as_view(), name ='pedido_eliminar'),
   


    ]

app_resit/aplicaciones/producto/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.producto.views import ProductoList, ProductoCreate , ProductoUpdate, ProductoDelete

urlpatterns = [
# url(r'^$', index, name='index'), 
      #url(r'^$', cliente_list, name ='cliente_listar'),
      #url(r'^nuevo$', cliente_view, name ='cliente_crear'),
      url(r'^nuevo$', ProductoCreate.as_view(), name ='producto_crear'),
      url(r'^$', ProductoList.as_view(), name ='producto_listar'),
      url(r'^listar$', ProductoList.as_view(), name ='producto_listar'),
#      url(r'^$', StockList.as_view(), name ='pedido_listar'),
 #     url(r'^listar$', StockList.as_view(), name ='pedido_listar'),
      url(r'^editar/(?P<pk>\d+)/$', ProductoUpdate.as_view(), name ='producto_editar'),
      url(r'^eliminar/(?P<pk>\d+)/$', ProductoDelete.as_view(), name ='producto_eliminar'),
      #url(r'^eliminar/(?P<id_prod>\d+)/$', ProductoDelete.as_view(), name ='producto_eliminar'),




    ]

app_resit/aplicaciones/stock/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.stock.views import  StockList

urlpatterns = [

   
      url(r'^$', StockList.as_view(), name ='stock_listar'),
      url(r'^listar$', StockList.as_view(), name ='stock_listar'),
     



    ]

app_resit/app_resit/urls.py
from django.conf.urls import handler404,handler500
from django.conf.urls import url, include
from django.contrib import admin
from app_resit import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('aplicaciones.pedido.urls', namespace="pedido")),
    url(r'^cliente/', include('aplicaciones.cliente.urls', namespace="cliente")),
    url(r'^logistica/', include('aplicaciones.logistica.urls', namespace="logistica")),
    url(r'^producto/', include('aplicaciones.producto.urls', namespace="producto")),
    url(r'^pedido/', include('aplicaciones.pedido.urls', namespace="pedido2")),
    url(r'^stock/', include('aplicaciones.stock.urls', namespace="stock")),
    url(r'^dashboard/', include('aplicaciones.dashboard.urls', namespace="dashboard")),
]

handler404 = 'views.custom_404'
handler500 = 'views.custom_500'

app_resit/templates/base/base.html
{% load static %}
<html><head>
    <meta charset="UTF-8">
    <title>{% block titulo %} Titulo {% endblock %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css">
    <!-- Font Awesome Icons -->
    <link href="{% static 'bootstrap/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
    <!-- Ionicons -->
    <link href="{% static 'bootstrap/css/ionicons.min.css'%}" rel="stylesheet" type="text/css">
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css'%}" rel="stylesheet" type="text/css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css'%}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-blue">
    <!-- Site wrapper -->
    <div class="wrapper">

      <header class="main-header">
        <a href="index2.html" class="logo"><b>RESIT</b></a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                
                <ul class="dropdown-menu">
                  <li class="header">You have 4 messages</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;"><ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                 <!--     <li><!-- start message -->
                     <!--   <a href="#">
                          <div class="pull-left">
                            <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                          </div>
                          <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li><!-- end message -->
                    </ul><div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 3px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px;"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div></div>
                  </li>
                  <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
           <!--   <li class="dropdown notifications-menu">
                
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                 <!--   <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;"><ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                    <!--  <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                    </ul><div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 3px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px;"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div></div>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- Tasks: style can be found in dropdown.less -->
            <!--  <li class="dropdown tasks-menu">
                
                <ul class="dropdown-menu">
                  <li class="header">You have 9 tasks</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                  <!--  <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;"><ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                      <li><!-- Task item -->
             <!--           <a href="#">
                          <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
           <!--         </ul><div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 3px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px;"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div></div>
                  </li>
                  <li class="footer">
                    <a href="#">View all tasks</a>
                  </li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->

            </ul>
          </div>
        </nav>
      </header>

      <!-- =============================================== -->

      <!-- Left side column. contains the sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="height: auto;">
          <!-- Sidebar user panel -->

          <!-- search form -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="seach" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">

            <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
              </ul>
            </li>
              <li class="treeview">
              <a href="#">
                <i class="fa fa-shopping-cart"></i> <span>Pedidos</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              <li><a href="{% url 'pedido:pedido_crear' %}"><i class="fa fa-circle-o"></i> Nuevo </a></li>
                <li><a href="{% url 'pedido:pedido_listar' %}"><i class="fa fa-circle-o"></i> Pedidos en linea</a></li>
                
              </ul>
            </li>

                  <li class="treeview">
              <a href="#">
                <i class="fa fa-users"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
               <li><a href="{% url 'cliente:cliente_crear' %}"><i class="fa fa-circle-o"></i> Nuevo </a></li>
                <li><a href="{% url 'cliente:cliente_listar' %}"><i class="fa fa-circle-o"></i> Clientes Registrados</a></li>
               
              </ul>
            </li>

                 <li class="treeview">
              <a href="#">
                <i class="fa fa-barcode"></i> <span>Productos</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              <li><a href="{% url 'producto:producto_crear' %}"><i class="fa fa-circle-o"></i> Nuevo </a></li>
                <li><a href="{% url 'producto:producto_listar' %}"><i class="fa fa-circle-o"></i> Productos en el Sistema</a></li>
                
                <li><a href="{% url 'stock:stock_listar' %}"><i class="fa fa-circle-o"></i> Stock Disponible</a></li>
              </ul>
            </li>

                 <li class="treeview">
              <a href="#">
                <i class="fa fa-truck"></i> <span>Transporte</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              <li><a href="{% url 'logistica:logistica_crear' %}"><i class="fa fa-circle-o"></i> Nuevo </a></li>
                <li><a href="{% url 'logistica:logistica_listar' %}"><i class="fa fa-circle-o"></i> Transportes Registrados</a></li>
                
          
              </ul>
            </li>




<!--            <li>
              <a href="../widgets.html">
                <i class="fa fa-th"></i> <span>Widgets</span> <small class="label pull-right bg-green">Hot</small>
              </a>
            </li> -->

          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- =============================================== -->

      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper" style="min-height: 954px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            {% block subtitulo %} {% endblock subtitulo %}
           <!-- <small>it all starts here</small> -->
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">
            <div class="box-header with-border">
              {% block titulo_panel %}<h3 class="box-title">
              </h3>{% endblock titulo_panel %}
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <div class="box-body">
              {% block content %}<h5> Bloque del contenido </h5>{% endblock %}
            </div><!-- /.box-body -->
            <div class="box-footer">
              
            </div><!-- /.box-footer-->
          </div><!-- /.box -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0
        </div>
        <strong>Copyright © 2017 <a href="http://almsaeedstudio.com">cesborquez@gmail.com</a>.</strong> All rights reserved.
      </footer>
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.3 -->
    <script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js'%}"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimScroll.min.js'%}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.min.js'%}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js'%}" type="text/javascript"></script>



</body></html>

app_resit/templates/base/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block titulo %} Titulo {% endblock %}</title>
    <link rel="stylesheet"  href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet"  href="{% static 'css/shop-item.css'%}">
    <link rel="stylesheet"  href="{% static 'css/font-awesome.min.css'%}">

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
     
            {% block navbar %}
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Resit</a>
            </div>

            <div class="nav navbar-nav navbar-right" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
            </div>
            {% endblock navbar %}
       
        </div>

    </nav>

    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead"><img src="{% static 'img/logo2.png'%}" class="img-responsive" style ="width:250px;"> <br></p>
                {% block submenu %}	
                <div class="list-group">
                    <a href="{% url 'pedido:pedido_listar' %} " class="list-group-item"> <i class="fa fa-shopping-cart" aria-hidden="true"></i> Pedidos</a>
                    <a href="{% url 'cliente:cliente_listar' %} " class="list-group-item "><i class="fa fa-users" aria-hidden="true"></i> Clientes</a>
                    <a href="{% url 'logistica:logistica_listar' %} " class="list-group-item"><i class="fa fa-truck" aria-hidden="true"></i> Transporte</a>
                    
                    <a href="{% url 'producto:producto_listar' %} " class="list-group-item"><i class="fa fa-product-hunt" aria-hidden="true"></i> Producto</a>

                     <a href="{% url 'stock:stock_listar' %} " class="list-group-item"><i class="fa fa-database" aria-hidden="true"></i> Stock</a>


                    
                </div>
                 {% endblock submenu %}
            </div>
            <br><br>

            <div class="col-md-9">
          {% block subtitulo %} <h2>subtitulo</h2> {% endblock subtitulo %}
          <br>
         
          <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-9 ">
                   <div class="text-right">
                   {% block cpanel %}
                   
                   {% endblock cpanel %}</div>
              </div>
          </div>
              
          
          <br>
             {% block content %}<h5> Bloque del contenido </h5>{% endblock %}
            </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                <h5> <p>Copyright &copy; cesborquez | 2017</p> </h5>
                    
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
     <script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js'%}"></script>
   

</body>

</html>