app_resit/aplicaciones/producto/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.producto.views import ProductoList, ProductoCreate , ProductoUpdate, ProductoDelete

urlpatterns = [
# url(r'^$', index, name='index'), 
      #url(r'^$', cliente_list, name ='cliente_listar'),
      #url(r'^nuevo$', cliente_view, name ='cliente_crear'),
      url(r'^nuevo$', ProductoCreate.as_view(), name ='producto_crear'),
      url(r'^$', ProductoList.as_view(), name ='producto_listar'),
      url(r'^listar$', ProductoList.as_view(), name ='producto_listar'),
#      url(r'^$', StockList.as_view(), name ='pedido_listar'),
 #     url(r'^listar$', StockList.as_view(), name ='pedido_listar'),
      url(r'^editar/(?P<pk>\d+)/$', ProductoUpdate.as_view(), name ='producto_editar'),
      url(r'^eliminar/(?P<pk>\d+)/$', ProductoDelete.as_view(), name ='producto_eliminar'),
      #url(r'^eliminar/(?P<id_prod>\d+)/$', ProductoDelete.as_view(), name ='producto_eliminar'),




    ]

app_resit/app_resit/urls.py
from django.conf.urls import handler404,handler500
from django.conf.urls import url, include
from django.contrib import admin
from app_resit import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('aplicaciones.pedido.urls', namespace="pedido")),
    url(r'^cliente/', include('aplicaciones.cliente.urls', namespace="cliente")),
    url(r'^logistica/', include('aplicaciones.logistica.urls', namespace="logistica")),
    url(r'^producto/', include('aplicaciones.producto.urls', namespace="producto")),
    url(r'^pedido/', include('aplicaciones.pedido.urls', namespace="pedido2")),
    url(r'^stock/', include('aplicaciones.stock.urls', namespace="stock")),
    url(r'^dashboard/', include('aplicaciones.dashboard.urls', namespace="dashboard")),
]

handler404 = 'views.custom_404'
handler500 = 'views.custom_500'

app_resit/aplicaciones/producto/models.py
from django.db import models



class Producto (models.Model):
	id_prod 	= models.AutoField(primary_key=True)
	nombre		= models.CharField(max_length=50)

	def __str__(self):
		return '{} '.format( self.nombre)

app_resit/aplicaciones/producto/forms.py
from django import forms

from aplicaciones.producto.models import Producto



class ProductoForm(forms.ModelForm):
	class Meta:
		model = Producto

		fields =[
		'nombre',
	

		]

		labels = {

		'nombre':'Nombre',


		}

		widgets = {
		'nombre': forms.TextInput(attrs={'class':'form-control'}),
	


		}

app_resit/aplicaciones/producto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, CreateView,UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from aplicaciones.producto.models import Producto
from aplicaciones.producto.forms import ProductoForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class ProductoList (ListView):
	model = Producto
	template_name = 'producto/producto_list.html'
	ordering = ['id_prod']
	paginate_by = 3



class ProductoCreate(CreateView):
	model = Producto
	form_class = ProductoForm
	template_name = 'producto/producto_reg.html'
	success_url	 = reverse_lazy('producto:producto_listar')

class ProductoUpdate(UpdateView):
	model  = Producto
	form_class = ProductoForm
	template_name = 'producto/producto_reg.html'
	success_url	 = reverse_lazy('producto:producto_listar')

class ProductoDelete(DeleteView):
	model  = Producto
	success_url	 = reverse_lazy('producto:producto_listar')









#class ProductoDelete(DeleteView):
#	model  = Producto
#	success_url	 = reverse_lazy('producto:producto_listar')

app_resit/templates/producto/producto_confirm_delete.html
	{% extends "base/base.html" %}

{% block subtitulo %}
	<h2>Eliminar Producto</h2>
{% endblock subtitulo %}

	{% block content %}
<div class="row">
	<div class="col-md-7">
		<form  method="post" accept-charset="utf-8">
			{% csrf_token %}
			<h3>¿Desea eliminar el registro de {{ producto.nombre }} ?</h3>

			<button type="submit" class="btn btn-danger float-right">Sí, eliminar</button> <a class="btn btn-default" href="{% url 'producto:producto_listar' %}">Cancelar </a>
		</form>
		</div>
	<div class="col-md-5">
	</div>
</div>

		{% endblock content %}

app_resit/templates/producto/producto_list.html
{% extends "base/base.html" %}
{% block titulo %}
  Producto
{% endblock titulo %}
{% block subtitulo %}
<h2>Productos en el sistema</h2>
{% endblock subtitulo %}

{% block cpanel %}
  <a class="btn btn-success right" href="{% url 'producto:producto_crear' %}"><i class="fa fa-plus" aria-hidden="true"></i> crear</a>
 
</ul>
{% endblock cpanel %}

{% block content %}
<table class="table table-bordered table-hover dataTable text-capitalize">
	
		{% if object_list %}
		<thead>
		<tr class="active">
			<td>#</td>
			<td>Nombre</td>
      <td>Cantidad</td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		{% for producto in object_list %}

			
		<tr>
			<td>{{ producto.id_prod }}</td>
			<td>{{ producto.nombre }}</td>
      <td>{{ producto.Stock.disponible }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'producto:producto_editar' producto.id_prod %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
			</td>
				<td>
				<a class="btn btn-danger" href="{% url 'producto:producto_eliminar' producto.id_prod %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
			</td>
		
		
		
		</tr>
			{% endfor %}

			{% else %}
			No hay registros en el sistema.

			{% endif %}


	</tbody>
</table>
 <!-- paginator -->
    {% if is_paginated %}
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
          <a href="?page={{ page_obj.previous_page_number }}">
            <span>Anterior</span>
          </a>
        </li>
        {% else %}
        <li class="disabled">
          <a href="#">
            <span>Anterior</span>
          </a>
        </li>
        {% endif %}

        {% for page in paginator.page_range %}
        <li {% if page == ProductoList.number %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li>
          <a href="?page={{ page_obj.next_page_number }}">
            <span>Siguiente</span>
          </a>
        </li>
        {% else %}
        <li {% if not ProductoList.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Siguiente</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    <!-- End pagintaor -->
	
{% endblock content %}

app_resit/templates/producto/producto_reg.html
{% extends "base/base.html" %}
{% block titulo %}
Registro de Producto
{% endblock titulo %}

{% block subtitulo %}
<h2>Registro de Producto</h2>

{% endblock subtitulo %}



		{% block content %}
<div class="row">
	<div class="col-md-7">
		<form  method="post" accept-charset="utf-8">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-success float-right">Guardar</button>
		</form>
		</div>
	<div class="col-md-5">
	</div>
</div>


		{% endblock content %}
	