app_resit/aplicaciones/logistica/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.logistica.views import LogisticaList, LogisticaCreate, LogisticaUpdate, LogisticaDelete

urlpatterns = [
		
	  url(r'^nuevo$', LogisticaCreate.as_view(), name ='logistica_crear'),  
      url(r'^$', LogisticaList.as_view(), name ='logistica_listar'),
      url(r'^listar$', LogisticaList.as_view(), name ='logistica_listar'),

      url(r'^editar/(?P<pk>\w+)/$', LogisticaUpdate.as_view(), name ='logistica_editar'),
      url(r'^eliminar/(?P<pk>\w+)/$', LogisticaDelete.as_view(), name ='logistica_eliminar'),
      



    ]

app_resit/app_resit/urls.py
from django.conf.urls import handler404,handler500
from django.conf.urls import url, include
from django.contrib import admin
from app_resit import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('aplicaciones.pedido.urls', namespace="pedido")),
    url(r'^cliente/', include('aplicaciones.cliente.urls', namespace="cliente")),
    url(r'^logistica/', include('aplicaciones.logistica.urls', namespace="logistica")),
    url(r'^producto/', include('aplicaciones.producto.urls', namespace="producto")),
    url(r'^pedido/', include('aplicaciones.pedido.urls', namespace="pedido2")),
    url(r'^stock/', include('aplicaciones.stock.urls', namespace="stock")),
    url(r'^dashboard/', include('aplicaciones.dashboard.urls', namespace="dashboard")),
]

handler404 = 'views.custom_404'
handler500 = 'views.custom_500'

app_resit/aplicaciones/logistica/models.py
from django.db import models

class Logistica (models.Model):
	patente 		= models.CharField(max_length=6, primary_key=True)
	estado			= models.IntegerField(default='0',editable=False)
	vehiculo 		= models.CharField(max_length=20)
	conductor		= models.CharField(max_length=50)

app_resit/aplicaciones/logistica/forms.py
from django import forms

from aplicaciones.logistica.models import Logistica



class LogisticaForm(forms.ModelForm):
	class Meta:
		model = Logistica

		fields =[
		'patente',
		'vehiculo',
		'conductor',

		]

		labels = {

		'patente'	:'Patente del Vehiculo',
		'vehiculo'	:'Marca del Vehiculo',
		'conductor'	:'Nombre Conductor',

		}

		widgets = {
		'patente'	: forms.TextInput(attrs={'class':'form-control'}),
		'vehiculo'	: forms.TextInput(attrs={'class':'form-control'}),
		'conductor'	: forms.TextInput(attrs={'class':'form-control'}),

		}

app_resit/aplicaciones/logistica/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, CreateView,UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from aplicaciones.logistica.models import Logistica
from aplicaciones.logistica.forms import LogisticaForm




class LogisticaCreate(CreateView):
	model = Logistica
	form_class = LogisticaForm
	template_name = 'logistica/logistica_reg.html'
	success_url	 = reverse_lazy('logistica:logistica_listar')

class LogisticaList (ListView):
	model = Logistica
	template_name = 'logistica/logistica_list.html'
	paginate_by = 3
	#ordering = ['estado']

class LogisticaUpdate(UpdateView):
	model  = Logistica
	form_class = LogisticaForm
	template_name = 'logistica/logistica_reg.html'
	success_url	 = reverse_lazy('logistica:logistica_listar')

class LogisticaDelete(DeleteView):
	model  = Logistica
	success_url	 = reverse_lazy('logistica:logistica_listar')

app_resit/templates/logistica/logistica_confirm_delete.html
	{% extends "base/base.html" %}

{% block subtitulo %}
	<h2>Eliminar transporte</h2>
{% endblock subtitulo %}

	{% block content %}
<div class="row">
	<div class="col-md-7">
		<form  method="post" accept-charset="utf-8">
			{% csrf_token %}
			<h3>¿Desea eliminar el Transporte Patente {{ logistica.patente }}, correspondiente al conductor {{ logistica.conductor }}?</h3>

			<button type="submit" class="btn btn-danger float-right">Sí, eliminar</button> <a class="btn btn-default" href="{% url 'logistica:logistica_listar' %}">Cancelar </a>
		</form>
		</div>
	<div class="col-md-5">
	</div>
</div>

		{% endblock content %}

app_resit/templates/logistica/logistica_list.html
{% extends "base/base.html" %}
{% block titulo %}
	Transporte
{% endblock titulo %}
{% block subtitulo %}
<h2>Transporte en el sistema</h2>
{% endblock subtitulo %}
{% block cpanel %}
  <a class="btn btn-success right" href="{% url 'logistica:logistica_crear' %}"><i class="fa fa-plus" aria-hidden="true"></i> crear</a>
{% endblock cpanel %}

{% block content %}


<table class="table table-bordered table-hover dataTable text-capitalize">
	{% if object_list %}
	<thead>
		<tr class="active">
			<td>Conductor</td>
			<td>Patente</td>
			<td>Vehiculo</td>
			<td>Estado</td>
			<td></td>
			<td></td>
		</tr>
	</thead>
		{% for logistica in object_list %}
	
	<tbody>
	
			
		<tr>
			<td>{{ logistica.conductor }}</td>
			<td>{{ logistica.patente }}</td>
			<td>{{ logistica.vehiculo }}</td>

			{%if logistica.estado == 0%}
			<td>Disponible</td>
			
			{%else%}
			<td>Ocupado</td>
			{% endif %}
		</td>
		<td>
				<a class="btn btn-primary" href="{% url 'logistica:logistica_editar' logistica.patente %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
			</td>
				<td>
				<a class="btn btn-danger" href="{% url 'logistica:logistica_eliminar' logistica.patente %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
			</td>
		
	
		</tr>
			{% endfor %}

			{% else %}
			  No hay registros en el sistema.

			{% endif %}
	</tbody>
</table>
<!-- paginator -->
    {% if is_paginated %}
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
          <a href="?page={{ page_obj.previous_page_number }}">
            <span>Anterior</span>
          </a>
        </li>
        {% else %}
        <li class="disabled">
          <a href="#">
            <span>Anterior</span>
          </a>
        </li>
        {% endif %}

        {% for page in paginator.page_range %}
        <li {% if page == LogisticaList.number %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li>
          <a href="?page={{ page_obj.next_page_number }}">
            <span>Siguiente</span>
          </a>
        </li>
        {% else %}
        <li {% if not LogisticaList.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Siguiente</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    <!-- End pagintaor -->
	
{% endblock content %}

app_resit/templates/logistica/logistica_reg.html
{% extends "base/base.html" %}
{% block titulo %}
Registro de Transporte
{% endblock titulo %}

{% block subtitulo %}
<h2>Registro Transporte</h2>

{% endblock subtitulo %}



		{% block content %}
<div class="row">
	<div class="col-md-7">
		<form  method="post" accept-charset="utf-8">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-success float-right">Guardar</button>
		</form>
		</div>
	<div class="col-md-5">
	</div>
</div>


		{% endblock content %}
	