app_resit/aplicaciones/logistica/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.logistica.views import LogisticaList, LogisticaCreate, LogisticaUpdate, LogisticaDelete

urlpatterns = [
		
	  url(r'^nuevo$', LogisticaCreate.as_view(), name ='logistica_crear'),  
      url(r'^$', LogisticaList.as_view(), name ='logistica_listar'),
      url(r'^listar$', LogisticaList.as_view(), name ='logistica_listar'),

      url(r'^editar/(?P<pk>\w+)/$', LogisticaUpdate.as_view(), name ='logistica_editar'),
      url(r'^eliminar/(?P<pk>\w+)/$', LogisticaDelete.as_view(), name ='logistica_eliminar'),
      



    ]

app_resit/aplicaciones/pedido/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include

from aplicaciones.pedido.views import PedidoCreate, PedidoList, PedidoUpdate , PedidoDelete

urlpatterns = [

    	url(r'^nuevo$', PedidoCreate.as_view(), name ='pedido_crear'),
      	url(r'^$', PedidoList.as_view(), name ='pedido_listar'),
      	url(r'^listar$', PedidoList.as_view(), name ='pedido_listar'),


      url(r'^editar/(?P<pk>\d+)/$', PedidoUpdate.as_view(), name ='pedido_editar'),
      url(r'^eliminar/(?P<pk>\d+)/$', PedidoDelete.as_view(), name ='pedido_eliminar'),
   


    ]

app_resit/app_resit/urls.py
from django.conf.urls import handler404,handler500
from django.conf.urls import url, include
from django.contrib import admin
from app_resit import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('aplicaciones.pedido.urls', namespace="pedido")),
    url(r'^cliente/', include('aplicaciones.cliente.urls', namespace="cliente")),
    url(r'^logistica/', include('aplicaciones.logistica.urls', namespace="logistica")),
    url(r'^producto/', include('aplicaciones.producto.urls', namespace="producto")),
    url(r'^pedido/', include('aplicaciones.pedido.urls', namespace="pedido2")),
    url(r'^stock/', include('aplicaciones.stock.urls', namespace="stock")),
    url(r'^dashboard/', include('aplicaciones.dashboard.urls', namespace="dashboard")),
]

handler404 = 'views.custom_404'
handler500 = 'views.custom_500'

app_resit/aplicaciones/pedido/models.py
from django.db import models

from aplicaciones.producto.models   import Producto
from aplicaciones.logistica.models 	import Logistica
from aplicaciones.cliente.models 	import Cliente


class Pedido (models.Model):
	codigo		 	= models.AutoField(primary_key=True)
	fecha_pedido 	= models.DateTimeField(auto_now=True)
	fecha_confir	= models.DateTimeField(null=True,editable=False)
	fecha_entrega	= models.DateTimeField(null=True,editable=False)
	estado			= models.IntegerField(default='0',editable=False)
	cantidad 		= models.IntegerField(blank=True,)
	Producto 		= models.ForeignKey(Producto, null=True, blank=True, on_delete=models.CASCADE)
	Logistica 		= models.ForeignKey(Logistica, null=True, blank=True, on_delete=models.CASCADE)
	Cliente    	    = models.ForeignKey(Cliente, null=True, blank=True, on_delete=models.CASCADE)

	

app_resit/aplicaciones/pedido/forms.py
from django import forms

from aplicaciones.pedido.models import Pedido




class PedidoForm(forms.ModelForm):
	class Meta:
		model = Pedido

		fields =[
		'Cliente',
		'Producto',
		'cantidad',

	

		]

		labels = {

		'Cliente':'Cliente',
		'Producto':'Producto',
		'cantidad':'cantidad',


		}

		widgets = {
		'Cliente': forms.Select(attrs={'class':'form-control'}),
		'Producto': forms.Select(attrs={'class':'form-control'}),
		'cantidad': forms.TextInput(attrs={'class':'form-control'}),
	

		}

app_resit/aplicaciones/pedido/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, CreateView,UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from aplicaciones.pedido.models import Pedido
from aplicaciones.pedido.forms import PedidoForm


class PedidoList (ListView):
	model = Pedido
	template_name = 'pedido/pedido_list.html'
	ordering = ['fecha_pedido']
	paginate_by = 5

class PedidoCreate(CreateView):
	model = Pedido
	form_class = PedidoForm
	template_name = 'pedido/pedido_reg.html'
	success_url	 = reverse_lazy('pedido:pedido_listar')

class PedidoUpdate(UpdateView):
	model  = Pedido
	form_class = PedidoForm
	template_name = 'pedido/pedido_reg.html'
	success_url	 = reverse_lazy('pedido:pedido_listar')

class PedidoDelete(DeleteView):
	model  = Pedido
	success_url	 = reverse_lazy('pedido:pedido_listar')

app_resit/templates/pedido/pedido_confirm_delete.html
	{% extends "base/base.html" %}

{% block subtitulo %}
	<h2>Eliminar transporte</h2>
{% endblock subtitulo %}

	{% block content %}
<div class="row">
	<div class="col-md-7">
		<form  method="post" accept-charset="utf-8">
			{% csrf_token %}
			<h3>¿Desea eliminar el Transporte Patente {{ logistica.patente }}, correspondiente al conductor {{ logistica.conductor }}?</h3>

			<button type="submit" class="btn btn-danger float-right">Sí, eliminar</button> <a class="btn btn-default" href="{% url 'logistica:logistica_listar' %}">Cancelar </a>
		</form>
		</div>
	<div class="col-md-5">
	</div>
</div>

		{% endblock content %}

app_resit/templates/pedido/pedido_list.html
{% extends "base/base.html" %}

{% block titulo %}
	Pedido
{% endblock titulo %}
{% block subtitulo %}
<h2>Pedidos del sistema</h2>
{% endblock subtitulo %}

{% block cpanel %}
  <a class="btn btn-success right" href="{% url 'pedido:pedido_crear' %}"><i class="fa fa-plus" aria-hidden="true"></i> crear</a>
{% endblock cpanel %}
{% block content %}


<table class="table table-bordered table-hover dataTable text-capitalize">
	{% if object_list %}
		<thead>
		<tr class="active">
			<td>#</td>
			<td>Fecha Pedido</td>
			<td>Estado</td>
			<td>Cliente</td>
			<td>Logistica</td>
			<td>Producto</td>
			<td>cantidad</td>
			<td></td>
			<td></td>
		</tr>
	</thead>
		{% for pedido in object_list %}

	<tbody>
	
			
		<tr>
			<td>{{ pedido.codigo}}</td>
			<td>{{ pedido.fecha_pedido }}</td>

			{%if pedido.estado == 0 %}
			<td><span class="label label-warning">Pendiente</span></td>
			{%elif pedido.estado == 1 %}
			<td><span class="label label-primary">En Ruta</span></td>
			{%elif pedido.estado == 2 %}
			<td><span class="label label-success">Entregado</span></td>
			{%else%}
			<td><span class="label label-danger">Cancelado</span></td>
			{%endif%}

			<td>{{ pedido.Cliente.nombre }}</td>

		
			{%if pedido.Logistica.patente is null%}
			<td><span class="label label-warning">Pendiente</span></td>
			{%else%}
			
			<td><span class="label label-success">{{ pedido.Logistica.patente }}</span></td>
			{%endif%}
		

			<td>{{ pedido.Producto.nombre }}</td>
			<td>{{ pedido.cantidad }}</td>
				<td>
				<a class="btn btn-primary" href="{% url 'pedido:pedido_editar' pk=pedido.codigo %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
			</td>
				<td>
				<a class="btn btn-danger" href="{% url 'pedido:pedido_eliminar' pk=pedido.codigo %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
			</td>
		
		
		</tr>
			{% endfor %}

			{% else %}
			 No hay registros en el sistema. 

			{% endif %}
	</tbody>
</table>
 <!-- paginator -->
    {% if is_paginated %}
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
          <a href="?page={{ page_obj.previous_page_number }}">
            <span>Anterior</span>
          </a>
        </li>
        {% else %}
        <li class="disabled">
          <a href="#">
            <span>Anterior</span>
          </a>
        </li>
        {% endif %}

        {% for page in paginator.page_range %}
        <li {% if page == PedidoList.number %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li>
          <a href="?page={{ page_obj.next_page_number }}">
            <span>Siguiente</span>
          </a>
        </li>
        {% else %}
        <li {% if not PedidoList.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Siguiente</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    <!-- End pagintaor -->
	
{% endblock content %}

app_resit/templates/pedido/pedido_reg.html
{% extends "base/base.html" %}
{% block titulo %}
Registro de Pedido
{% endblock titulo %}

{% block subtitulo %}
<h2>Registro Pedido</h2>

{% endblock subtitulo %}



		{% block content %}
<div class="row">
	<div class="col-md-7">
		<form  method="post" accept-charset="utf-8">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-success float-right">Guardar</button>
		</form>
		</div>
	<div class="col-md-5">
	</div>
</div>


		{% endblock content %}
	